### ISSUE TITLE
Sort ordering of items wrong in a couple cases still after last update

### ISSUE THREAD

**Issue by cecilkilmer** [jefflomacy/villagerdb#198] opened 2020-04-29 22:37 UTC
Possible follow-on from #184 

I noticed my list here:
https://villagerdb.com/user/cecilkilmer/list/clothing
Has a sort order issue compared to the game.  While 184 is correctly fixed, I noticed that "Ribbon sandals" is being ordered before "Ribbon" in my above list.  Since Ribbon's string is shorter, it should be listed first (all characters match until the "Ribbon" string hits the null-terminator, so it should be alphabetically first).

**Comment by jefflomacy** [comment] 2020-04-29 22:40
I see what the problem is here. It's because internally it's sorting by the variation ID after the item ID but it is not a tie-breaking sort. I will assess this locally and see if I can resolve it easily and if so it'll go up tomorrow.

**Comment by jefflomacy** [comment] 2020-04-29 23:03
Should hopefully be fixed now. Sort function uses variation ID as a tie breaker, in theory, instead of treating them both as one unit. I'll reply when this goes up and have you let me know.

**Comment by jefflomacy** [comment] 2020-04-30 10:57
Can you confirm this is fixed now?

**Comment by jefflomacy** [comment] 2020-05-03 15:50
Haven't heard back so assuming no news is good news. Let us know if it recurs.

**Closed by jefflomacy** 2020-05-03 15:50 UTC
