### ISSUE TITLE
grass standee recipe checkbox/label is right-aligned

### ISSUE THREAD

**Issue by kwalker314** [jefflomacy/villagerdb#246] opened 2020-05-16 17:45 UTC
this doesn't seem to be the case anywhere else, but it looks weird idk
![image](https://user-images.githubusercontent.com/5703527/82126540-0dfdee00-9773-11ea-9700-327621ae13cc.png)

**Comment by jefflomacy** [comment] 2020-05-31 19:06
The checkbox is right aligned on any item that has a dropdown menu. This is by design. It has some flaws and we could discuss revision of it in the future. As of right now, this entire component is awaiting refactoring so I'm going to close this and it can be re-opened for discussion when this component eventually gets refactored to support the concept of default lists.

**Closed by jefflomacy** 2020-05-31 19:06 UTC
